# Generated by Django 4.1.7 on 2023-04-03 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0016_alter_usersignup_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 23, 20, 20, 113222))),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='Uploaded_Files')),
            ],
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 23, 20, 20, 113222)),
        ),
    ]
