# Generated by Django 4.1.7 on 2023-04-04 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0019_remove_feedback_subject_alter_feedback_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 16, 25, 52, 650122)),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 16, 25, 52, 649125)),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 4, 16, 25, 52, 648124)),
        ),
    ]
